// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mytable.proto

#ifndef PROTOBUF_INCLUDED_mytable_2eproto
#define PROTOBUF_INCLUDED_mytable_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mytable_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_mytable_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
namespace mytable {
class MyAddress;
class MyAddressDefaultTypeInternal;
extern MyAddressDefaultTypeInternal _MyAddress_default_instance_;
class MyTable;
class MyTableDefaultTypeInternal;
extern MyTableDefaultTypeInternal _MyTable_default_instance_;
}  // namespace mytable
namespace google {
namespace protobuf {
template<> ::mytable::MyAddress* Arena::CreateMaybeMessage<::mytable::MyAddress>(Arena*);
template<> ::mytable::MyTable* Arena::CreateMaybeMessage<::mytable::MyTable>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace mytable {

// ===================================================================

class MyAddress :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:mytable.MyAddress) */ {
 public:
  MyAddress();
  virtual ~MyAddress();

  MyAddress(const MyAddress& from);

  inline MyAddress& operator=(const MyAddress& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MyAddress(MyAddress&& from) noexcept
    : MyAddress() {
    *this = ::std::move(from);
  }

  inline MyAddress& operator=(MyAddress&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const MyAddress& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MyAddress* internal_default_instance() {
    return reinterpret_cast<const MyAddress*>(
               &_MyAddress_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MyAddress* other);
  friend void swap(MyAddress& a, MyAddress& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MyAddress* New() const final {
    return CreateMaybeMessage<MyAddress>(nullptr);
  }

  MyAddress* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MyAddress>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const MyAddress& from);
  void MergeFrom(const MyAddress& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MyAddress* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string label = 1;
  void clear_label();
  static const int kLabelFieldNumber = 1;
  const ::std::string& label() const;
  void set_label(const ::std::string& value);
  #if LANG_CXX11
  void set_label(::std::string&& value);
  #endif
  void set_label(const char* value);
  void set_label(const char* value, size_t size);
  ::std::string* mutable_label();
  ::std::string* release_label();
  void set_allocated_label(::std::string* label);

  // string address = 2;
  void clear_address();
  static const int kAddressFieldNumber = 2;
  const ::std::string& address() const;
  void set_address(const ::std::string& value);
  #if LANG_CXX11
  void set_address(::std::string&& value);
  #endif
  void set_address(const char* value);
  void set_address(const char* value, size_t size);
  ::std::string* mutable_address();
  ::std::string* release_address();
  void set_allocated_address(::std::string* address);

  // @@protoc_insertion_point(class_scope:mytable.MyAddress)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr label_;
  ::google::protobuf::internal::ArenaStringPtr address_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mytable_2eproto;
};
// -------------------------------------------------------------------

class MyTable :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:mytable.MyTable) */ {
 public:
  MyTable();
  virtual ~MyTable();

  MyTable(const MyTable& from);

  inline MyTable& operator=(const MyTable& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MyTable(MyTable&& from) noexcept
    : MyTable() {
    *this = ::std::move(from);
  }

  inline MyTable& operator=(MyTable&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const MyTable& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MyTable* internal_default_instance() {
    return reinterpret_cast<const MyTable*>(
               &_MyTable_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(MyTable* other);
  friend void swap(MyTable& a, MyTable& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MyTable* New() const final {
    return CreateMaybeMessage<MyTable>(nullptr);
  }

  MyTable* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MyTable>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const MyTable& from);
  void MergeFrom(const MyTable& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MyTable* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // .mytable.MyAddress address = 3;
  bool has_address() const;
  void clear_address();
  static const int kAddressFieldNumber = 3;
  const ::mytable::MyAddress& address() const;
  ::mytable::MyAddress* release_address();
  ::mytable::MyAddress* mutable_address();
  void set_allocated_address(::mytable::MyAddress* address);

  // int64 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:mytable.MyTable)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::mytable::MyAddress* address_;
  ::google::protobuf::int64 id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mytable_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MyAddress

// string label = 1;
inline void MyAddress::clear_label() {
  label_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MyAddress::label() const {
  // @@protoc_insertion_point(field_get:mytable.MyAddress.label)
  return label_.GetNoArena();
}
inline void MyAddress::set_label(const ::std::string& value) {
  
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mytable.MyAddress.label)
}
#if LANG_CXX11
inline void MyAddress::set_label(::std::string&& value) {
  
  label_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mytable.MyAddress.label)
}
#endif
inline void MyAddress::set_label(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mytable.MyAddress.label)
}
inline void MyAddress::set_label(const char* value, size_t size) {
  
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mytable.MyAddress.label)
}
inline ::std::string* MyAddress::mutable_label() {
  
  // @@protoc_insertion_point(field_mutable:mytable.MyAddress.label)
  return label_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MyAddress::release_label() {
  // @@protoc_insertion_point(field_release:mytable.MyAddress.label)
  
  return label_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MyAddress::set_allocated_label(::std::string* label) {
  if (label != nullptr) {
    
  } else {
    
  }
  label_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), label);
  // @@protoc_insertion_point(field_set_allocated:mytable.MyAddress.label)
}

// string address = 2;
inline void MyAddress::clear_address() {
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MyAddress::address() const {
  // @@protoc_insertion_point(field_get:mytable.MyAddress.address)
  return address_.GetNoArena();
}
inline void MyAddress::set_address(const ::std::string& value) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mytable.MyAddress.address)
}
#if LANG_CXX11
inline void MyAddress::set_address(::std::string&& value) {
  
  address_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mytable.MyAddress.address)
}
#endif
inline void MyAddress::set_address(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mytable.MyAddress.address)
}
inline void MyAddress::set_address(const char* value, size_t size) {
  
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mytable.MyAddress.address)
}
inline ::std::string* MyAddress::mutable_address() {
  
  // @@protoc_insertion_point(field_mutable:mytable.MyAddress.address)
  return address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MyAddress::release_address() {
  // @@protoc_insertion_point(field_release:mytable.MyAddress.address)
  
  return address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MyAddress::set_allocated_address(::std::string* address) {
  if (address != nullptr) {
    
  } else {
    
  }
  address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:mytable.MyAddress.address)
}

// -------------------------------------------------------------------

// MyTable

// int64 id = 1;
inline void MyTable::clear_id() {
  id_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 MyTable::id() const {
  // @@protoc_insertion_point(field_get:mytable.MyTable.id)
  return id_;
}
inline void MyTable::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:mytable.MyTable.id)
}

// string name = 2;
inline void MyTable::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MyTable::name() const {
  // @@protoc_insertion_point(field_get:mytable.MyTable.name)
  return name_.GetNoArena();
}
inline void MyTable::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mytable.MyTable.name)
}
#if LANG_CXX11
inline void MyTable::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mytable.MyTable.name)
}
#endif
inline void MyTable::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mytable.MyTable.name)
}
inline void MyTable::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mytable.MyTable.name)
}
inline ::std::string* MyTable::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:mytable.MyTable.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MyTable::release_name() {
  // @@protoc_insertion_point(field_release:mytable.MyTable.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MyTable::set_allocated_name(::std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:mytable.MyTable.name)
}

// .mytable.MyAddress address = 3;
inline bool MyTable::has_address() const {
  return this != internal_default_instance() && address_ != nullptr;
}
inline void MyTable::clear_address() {
  if (GetArenaNoVirtual() == nullptr && address_ != nullptr) {
    delete address_;
  }
  address_ = nullptr;
}
inline const ::mytable::MyAddress& MyTable::address() const {
  const ::mytable::MyAddress* p = address_;
  // @@protoc_insertion_point(field_get:mytable.MyTable.address)
  return p != nullptr ? *p : *reinterpret_cast<const ::mytable::MyAddress*>(
      &::mytable::_MyAddress_default_instance_);
}
inline ::mytable::MyAddress* MyTable::release_address() {
  // @@protoc_insertion_point(field_release:mytable.MyTable.address)
  
  ::mytable::MyAddress* temp = address_;
  address_ = nullptr;
  return temp;
}
inline ::mytable::MyAddress* MyTable::mutable_address() {
  
  if (address_ == nullptr) {
    auto* p = CreateMaybeMessage<::mytable::MyAddress>(GetArenaNoVirtual());
    address_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mytable.MyTable.address)
  return address_;
}
inline void MyTable::set_allocated_address(::mytable::MyAddress* address) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete address_;
  }
  if (address) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      address = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, address, submessage_arena);
    }
    
  } else {
    
  }
  address_ = address;
  // @@protoc_insertion_point(field_set_allocated:mytable.MyTable.address)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mytable

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_mytable_2eproto
